// Package envref is the single source of truth for every environment
// variable bpfcompat reads. The CLI's `bpfcompat env` subcommand renders it
// for operators; CI uses the same list to keep docs/env-reference.md
// in sync. Add a new env knob here whenever you wire one up in code so the
// catalog never drifts from reality.
package envref

import (
	"fmt"
	"sort"
	"strings"
)

// Var describes a single env-var contract. The Description should explain
// what setting the variable does AND when an operator should change it from
// the default — it's the line a senior reviewer reads in a runbook.
type Var struct {
	Name        string
	Default     string
	Description string
	Category    string
}

// All returns every documented env var, sorted by category then name.
// Callers shouldn't mutate the slice; copy if you need to filter.
func All() []Var {
	out := make([]Var, 0, len(catalog))
	out = append(out, catalog...)
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Category == out[j].Category {
			return out[i].Name < out[j].Name
		}
		return out[i].Category < out[j].Category
	})
	return out
}

// Markdown renders the catalog as a Markdown table grouped by category.
// We render here rather than at the call site so doc gen and the CLI agree.
func Markdown() string {
	var b strings.Builder
	b.WriteString("# Environment Reference\n\n")
	b.WriteString("Generated by `bpfcompat env --markdown`. Do not edit by hand.\n\n")
	currentCat := ""
	for _, v := range All() {
		if v.Category != currentCat {
			if currentCat != "" {
				b.WriteString("\n")
			}
			fmt.Fprintf(&b, "## %s\n\n", v.Category)
			b.WriteString("| Variable | Default | Description |\n")
			b.WriteString("|---|---|---|\n")
			currentCat = v.Category
		}
		def := v.Default
		if def == "" {
			def = "_(unset)_"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", v.Name, def, escapeMarkdown(v.Description))
	}
	return b.String()
}

func escapeMarkdown(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

// catalog is the curated list. Keep entries grouped by category and
// alphabetically within a category for diff-friendliness.
var catalog = []Var{
	// ---------- Logging ----------
	{
		Name: "BPFCOMPAT_LOG_FORMAT", Default: "json",
		Category:    "Logging",
		Description: "slog handler format: 'json' (default) for log shippers, 'text' for local dev.",
	},
	{
		Name: "BPFCOMPAT_LOG_LEVEL", Default: "info",
		Category:    "Logging",
		Description: "slog level filter: debug | info | warn | error.",
	},

	// ---------- Agent ----------
	{
		Name: "BPFCOMPAT_AGENT_IDENTITY_TOKEN", Default: "",
		Category:    "Agent",
		Description: "Optional identity JWT sent as X-API-Identity-Token by bpfcompat agent plan/apply when --identity-token is omitted.",
	},
	{
		Name: "BPFCOMPAT_AGENT_LAST_RESULT_PATH", Default: "",
		Category:    "Agent",
		Description: "Default path read by bpfcompat agent status when --path is omitted.",
	},
	{
		Name: "BPFCOMPAT_AGENT_LOAD_POLICY_PATH", Default: "",
		Category:    "Agent",
		Description: "Default local load-policy file used by bpfcompat agent apply --approve-load when --load-policy is omitted.",
	},
	{
		Name: "BPFCOMPAT_AGENT_REGISTRY_TOKEN", Default: "",
		Category:    "Agent",
		Description: "Default registry bearer token used by bpfcompat agent plan/apply when --registry-token is omitted.",
	},
	{
		Name: "BPFCOMPAT_AGENT_REQUIRE_LOAD_POLICY", Default: "true",
		Category:    "Agent",
		Description: "Require a local load policy before bpfcompat agent apply --approve-load. Disable only in controlled labs.",
	},

	// ---------- Auth (API) ----------
	{
		Name: "BPFCOMPAT_API_WRITE_KEY", Default: "",
		Category:    "Auth (API)",
		Description: "Pre-shared API key required by write endpoints when JWT identity is not configured. Compare is constant-time.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_REQUIRE_IDENTITY", Default: "false",
		Category:    "Auth (API)",
		Description: "When true, write endpoints require a valid X-API-Identity-Token JWT (API key alone is rejected).",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_HS256_SECRET", Default: "",
		Category:    "Auth (API)",
		Description: "Shared HS256 secret used to verify identity JWTs. Mutually exclusive with JWKS_URL/JWKS_PATH.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_JWKS_URL", Default: "",
		Category:    "Auth (API)",
		Description: "HTTPS URL serving a JWKS document. http:// is rejected.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_JWKS_PATH", Default: "",
		Category:    "Auth (API)",
		Description: "Filesystem path to a JWKS document (alternative to JWKS_URL).",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_OIDC_ISSUER_URL", Default: "",
		Category:    "Auth (API)",
		Description: "OIDC issuer URL; the discovery document is fetched to resolve jwks_uri. https:// only.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_ISSUER", Default: "",
		Category:    "Auth (API)",
		Description: "Expected 'iss' claim. When set, tokens with a mismatching issuer are rejected.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_AUDIENCE", Default: "",
		Category:    "Auth (API)",
		Description: "Expected 'aud' claim.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_JWKS_CACHE_TTL", Default: "5m",
		Category:    "Auth (API)",
		Description: "How long to cache the JWKS document before refreshing.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_JWKS_HTTP_TIMEOUT", Default: "5s",
		Category:    "Auth (API)",
		Description: "Per-request HTTP timeout when fetching JWKS/OIDC documents.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_OIDC_DISCOVERY_CACHE_TTL", Default: "10m",
		Category:    "Auth (API)",
		Description: "TTL on the OIDC discovery (jwks_uri) cache entry.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_REQUIRED_SCOPES", Default: "",
		Category:    "Auth (API)",
		Description: "Space- or comma-separated scopes that every JWT must carry.",
	},
	{
		Name: "BPFCOMPAT_API_WRITE_JWT_REQUIRED_ROLES", Default: "",
		Category:    "Auth (API)",
		Description: "Roles every JWT must carry.",
	},
	{
		Name: "BPFCOMPAT_API_ALLOW_ANONYMOUS_VALIDATE", Default: "false",
		Category:    "Auth (API)",
		Description: "Allow unauthenticated calls to /api/v1/validate (also implies anonymous read of /api/v1/validate/status).",
	},
	{
		Name: "BPFCOMPAT_API_ALLOW_ANONYMOUS_RUNTIME_DELIVERY", Default: "false",
		Category:    "Auth (API)",
		Description: "Allow unauthenticated /api/v1/runtime/select and /api/v1/runtime/fetch for public demos. Does not enable compare, registry writes, or runtime execute.",
	},
	{
		Name: "BPFCOMPAT_API_ALLOW_ANONYMOUS_WRITE", Default: "false",
		Category:    "Auth (API)",
		Description: "Allow unauthenticated calls to every write endpoint. Use only for local dev.",
	},
	{
		Name: "BPFCOMPAT_API_ALLOW_ANONYMOUS_READ", Default: "false",
		Category:    "Auth (API)",
		Description: "Allow unauthenticated reads of /api/v1/history/*, runtime probe, runtime decisions. Off by default.",
	},
	{
		Name: "BPFCOMPAT_API_MTLS_IDENTITY_MAP_PATH", Default: "",
		Category:    "Auth (API)",
		Description: "JSON file mapping verified mTLS client certificates to explicit API identities, tenants, projects, scopes, and roles. Required before mTLS can authenticate API requests.",
	},
	{
		Name: "BPFCOMPAT_API_REGISTRY_REQUIRE_IDENTITY", Default: "false",
		Category:    "Auth (API)",
		Description: "When true, every /api/v1/registry/* call must carry an identity JWT.",
	},

	// ---------- Runtime execute (security-critical) ----------
	{
		Name: "BPFCOMPAT_API_ENABLE_RUNTIME_EXECUTE", Default: "false",
		Category:    "Runtime Execute",
		Description: "Master switch for the host-load endpoint. Off by default; never enable on a multi-tenant host.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_KILL_SWITCH", Default: "false",
		Category:    "Runtime Execute",
		Description: "Emergency: when true, every /api/v1/runtime/execute call returns 503. Leaves the endpoint registered for audit.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_APPROVAL_TOKEN", Default: "",
		Category:    "Runtime Execute",
		Description: "Required value for the X-Execute-Approval-Token header. Constant-time compared.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_JWT_REQUIRED_SCOPES", Default: "",
		Category:    "Runtime Execute",
		Description: "Additional space- or comma-separated JWT scopes required specifically for /api/v1/runtime/execute.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_JWT_REQUIRED_ROLES", Default: "",
		Category:    "Runtime Execute",
		Description: "Additional JWT roles required specifically for /api/v1/runtime/execute.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_WORKER_USER", Default: "",
		Category:    "Runtime Execute",
		Description: "OS username to run the worker as via sudo -u. Leave empty to run as the API process user.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_WORKER_BINARY", Default: "",
		Category:    "Runtime Execute",
		Description: "Absolute path to the bpfcompat binary used as the worker. Defaults to os.Executable().",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_REQUIRE_WORKER_IDENTITY", Default: "false",
		Category:    "Runtime Execute",
		Description: "Refuse runtime execute if WORKER_USER is unset.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_POLICY_PATH", Default: "",
		Category:    "Runtime Execute",
		Description: "Path to a YAML policy file evaluated before each execute. See docs/runtime-execute-policy.md.",
	},
	{
		Name: "BPFCOMPAT_API_RUNTIME_EXECUTE_REQUIRE_POLICY", Default: "false",
		Category:    "Runtime Execute",
		Description: "Refuse runtime execute if no policy is configured (defense in depth).",
	},
	{
		Name: "BPFCOMPAT_API_REDACT_RUNTIME_DETAILS", Default: "true",
		Category:    "Runtime Execute",
		Description: "Redact filesystem paths in success and error responses. Disable only when debugging.",
	},

	// ---------- Validator ----------
	{
		Name: "BPFCOMPAT_VALIDATOR_BIN", Default: "",
		Category:    "Validator",
		Description: "Absolute path to the C validator binary; wins over the /usr/libexec search path.",
	},
	{
		Name: "BPFCOMPAT_VALIDATOR_SHA256", Default: "",
		Category:    "Validator",
		Description: "Expected SHA-256 of the validator binary. When set, mismatched binaries are refused before exec.",
	},

	// ---------- HTTP server ----------
	{
		Name: "BPFCOMPAT_API_ENABLE_METRICS", Default: "false",
		Category:    "HTTP Server",
		Description: "Expose /metrics (Prometheus) gated by read auth.",
	},
	{
		Name: "BPFCOMPAT_API_ENABLE_PPROF", Default: "false",
		Category:    "HTTP Server",
		Description: "Expose /debug/pprof/* runtime profiles gated by real API-key/JWT auth. Anonymous demo modes never open pprof. Off by default; exposes goroutine stacks and heap addresses when on.",
	},
	{
		Name: "BPFCOMPAT_API_CLIENT_CA_PATH", Default: "",
		Category:    "HTTP Server",
		Description: "When set, enables mutual TLS. File must contain PEM-encoded CA certs; every client must present a chain that verifies against this pool. Requires TLSCertPath/TLSKeyPath. Verified client cert CN is accepted as identity (AuthType=\"mtls\").",
	},
	{
		Name: "BPFCOMPAT_API_TRUSTED_PROXIES", Default: "",
		Category:    "HTTP Server",
		Description: "Comma-separated CIDRs of trusted upstream proxies. Only requests from these peers have X-Forwarded-For honored.",
	},
	{
		Name: "BPFCOMPAT_API_SHUTDOWN_DRAIN_TIMEOUT", Default: "10m",
		Category:    "HTTP Server",
		Description: "Maximum wait for in-flight validate jobs during graceful shutdown.",
	},
	{
		Name: "BPFCOMPAT_API_MAX_ACTIVE_VALIDATE_JOBS", Default: "2",
		Category:    "HTTP Server",
		Description: "Maximum concurrent VM-backed validate jobs. Hard cap is 64.",
	},
	{
		Name: "BPFCOMPAT_API_MAX_QUEUED_VALIDATE_JOBS", Default: "20",
		Category:    "HTTP Server",
		Description: "Maximum queued validate jobs. Beyond this, /api/v1/validate/start returns 429.",
	},
	{
		Name: "BPFCOMPAT_API_MAX_VALIDATE_CONCURRENCY", Default: "8",
		Category:    "HTTP Server",
		Description: "Per-job profile concurrency cap.",
	},
	{
		Name: "BPFCOMPAT_API_MAX_VALIDATE_PROFILES", Default: "32",
		Category:    "HTTP Server",
		Description: "Maximum profile selections per request.",
	},
	{
		Name: "BPFCOMPAT_API_MAX_VALIDATE_TIMEOUT", Default: "15m",
		Category:    "HTTP Server",
		Description: "Upper bound on the per-job timeout parameter.",
	},
	{
		Name: "BPFCOMPAT_API_SOURCE_COMPILE_TIMEOUT", Default: "30s",
		Category:    "HTTP Server",
		Description: "clang timeout when compiling source uploads.",
	},
	{
		Name: "BPFCOMPAT_API_SOURCE_COMPILE_ALLOW_EXTRA_FLAGS", Default: "false",
		Category:    "HTTP Server",
		Description: "Allow per-request extra -D/-U flags to clang. Off by default.",
	},
	{
		Name: "BPFCOMPAT_API_AUTO_SYNC_REGISTRY", Default: "false",
		Category:    "HTTP Server",
		Description: "Auto-publish completed validate runs into the cloud registry. Requires AUTO_SYNC_TENANT/PROJECT.",
	},
	{
		Name: "BPFCOMPAT_API_AUTO_SYNC_TENANT", Default: "",
		Category:    "HTTP Server",
		Description: "Tenant for auto-sync.",
	},
	{
		Name: "BPFCOMPAT_API_AUTO_SYNC_PROJECT", Default: "",
		Category:    "HTTP Server",
		Description: "Project for auto-sync.",
	},
	{
		Name: "BPFCOMPAT_API_AUTO_SYNC_PROJECT_VISIBILITY", Default: "private",
		Category:    "HTTP Server",
		Description: "Visibility applied when auto-sync creates the project: private | public.",
	},

	// ---------- Cloud registry ----------
	{
		Name: "BPFCOMPAT_REGISTRY_AUTH_TOKEN", Default: "",
		Category:    "Cloud Registry",
		Description: "Bootstrap superuser token. Use only for initial setup; rotate to per-tenant grants ASAP.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_AUTH_TOKEN_NOT_BEFORE", Default: "",
		Category:    "Cloud Registry",
		Description: "Optional RFC3339 not-before timestamp for the bootstrap superuser token.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_AUTH_TOKEN_EXPIRES_AT", Default: "",
		Category:    "Cloud Registry",
		Description: "Optional RFC3339 expiration timestamp for the bootstrap superuser token.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_AUDIT_MAX_BYTES", Default: "67108864",
		Category:    "Cloud Registry",
		Description: "Active audit-log size before rotation (bytes). 0 disables rotation.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_AUDIT_MAX_FILES", Default: "10",
		Category:    "Cloud Registry",
		Description: "Max rotated audit-log files retained (active file is additional).",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_RATE_LIMIT_MAX_REQUESTS", Default: "120",
		Category:    "Cloud Registry",
		Description: "Max requests per (subject, tenant, project, action) window. 0 disables rate limiting.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_RATE_LIMIT_WINDOW_SECONDS", Default: "60",
		Category:    "Cloud Registry",
		Description: "Rate-limit window length in seconds.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_MAX_ARTIFACT_BYTES", Default: "",
		Category:    "Cloud Registry",
		Description: "Per-artifact upload size cap.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_MAX_ARTIFACT_VERSIONS_PER_NAME", Default: "",
		Category:    "Cloud Registry",
		Description: "Max retained versions per artifact name. 0 disables.",
	},
	{
		Name: "BPFCOMPAT_REGISTRY_MAX_PROJECT_STORAGE_BYTES", Default: "",
		Category:    "Cloud Registry",
		Description: "Total bytes stored across all artifacts in a project.",
	},
	{
		Name: "BPFCOMPAT_RUNTIME_DECISIONS_MAX_BYTES", Default: "67108864",
		Category:    "Cloud Registry",
		Description: "runtime_decisions.jsonl rotation cap.",
	},
	{
		Name: "BPFCOMPAT_RUNTIME_DECISIONS_MAX_FILES", Default: "10",
		Category:    "Cloud Registry",
		Description: "runtime_decisions retention.",
	},

	// ---------- Artifact fetch ----------
	{
		Name: "BPFCOMPAT_FETCH_MAX_BYTES", Default: "134217728",
		Category:    "Artifact Fetch",
		Description: "Maximum HTTP artifact download size (bytes). Default 128 MiB.",
	},
	{
		Name: "BPFCOMPAT_FETCH_ALLOW_INTERNAL_HOSTS", Default: "false",
		Category:    "Artifact Fetch",
		Description: "Allow fetches that resolve to RFC1918 / loopback / link-local / cloud-metadata IPs. Off by default to block SSRF.",
	},
	{
		Name: "BPFCOMPAT_FETCH_ALLOW_FILE_URI", Default: "false",
		Category:    "Artifact Fetch",
		Description: "Allow file:// artifact URIs. Off by default; enable only for trusted on-host caches.",
	},

	// ---------- Signing ----------
	{
		Name: "BPFCOMPAT_SIGNING_MODE", Default: "local",
		Category:    "Signing",
		Description: "Where the registry signing key lives: 'local' (default, on disk) or 'external-cmd'.",
	},
	{
		Name: "BPFCOMPAT_SIGNING_EXTERNAL_CMD", Default: "",
		Category:    "Signing",
		Description: "Command to invoke for external signing. Stdin = canonical payload; stdout = signature envelope JSON.",
	},
	{
		Name: "BPFCOMPAT_SIGNING_EXTERNAL_ARGS", Default: "",
		Category:    "Signing",
		Description: "Whitespace-split extra args for the external signer.",
	},
	{
		Name: "BPFCOMPAT_TRUSTED_SIGNING_PUBLIC_KEYS", Default: "",
		Category:    "Signing",
		Description: "Inline trusted public keys (kid:base64, comma-separated).",
	},
	{
		Name: "BPFCOMPAT_TRUSTED_SIGNING_KEYS_PATH", Default: "",
		Category:    "Signing",
		Description: "Path to a keyring file (one trusted key per line).",
	},
}
