package vm

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

type Profile struct {
	ID           string `yaml:"id"`
	Distro       string `yaml:"distro"`
	Version      string `yaml:"version"`
	KernelFamily string `yaml:"kernel_family"`
	Arch         string `yaml:"arch"`
	Runner       string `yaml:"runner,omitempty"`
	// InstallKernel installs a specific kernel release inside the guest
	// before validation and reboots into it, so one base image yields a
	// dense per-release matrix instead of only the kernel the image
	// shipped with. Ubuntu (apt/grub) only for now; the release must be a
	// package-exact string such as "5.15.0-118-generic".
	InstallKernel string `yaml:"install_kernel,omitempty"`
	// KernelPackages lists direct .deb URLs to install instead of going
	// through apt. Required for kernel releases the distro has superseded:
	// they remain downloadable in the archive pool but disappear from the
	// apt indexes. Generated by `bpfcompat kernel-sweep` from the
	// kernel-crawler inventory.
	KernelPackages []string       `yaml:"kernel_packages,omitempty"`
	Image          ImageConfig    `yaml:"image"`
	VirtmeNG       VirtmeNGCfg    `yaml:"virtme_ng,omitempty"`
	Firecracker    FirecrackerCfg `yaml:"firecracker,omitempty"`
	Boot           BootConfig     `yaml:"boot"`
	Validator      ValidatorCfg   `yaml:"validator"`
	Capabilities   Capability     `yaml:"capabilities"`
}

type ImageConfig struct {
	SourceURL string `yaml:"source_url"`
	LocalPath string `yaml:"local_path"`
	// SHA256 optionally pins the expected image digest. When set, a
	// downloaded or cached image that does not match fails the run instead
	// of silently testing different bytes. Pinning requires a
	// release-versioned source_url — vendor "current" URLs mutate.
	SHA256 string `yaml:"sha256,omitempty"`
}

type VirtmeNGCfg struct {
	Run       string   `yaml:"run"`
	ExtraArgs []string `yaml:"extra_args,omitempty"`
}

type FirecrackerCfg struct {
	KernelImagePath string `yaml:"kernel_image_path"`
	RootfsPath      string `yaml:"rootfs_path,omitempty"`
	InitrdPath      string `yaml:"initrd_path,omitempty"`
	BootArgs        string `yaml:"boot_args,omitempty"`
	GuestMAC        string `yaml:"guest_mac,omitempty"`
	TapDevice       string `yaml:"tap_device,omitempty"`
}

type BootConfig struct {
	MemoryMB int `yaml:"memory_mb"`
	CPUs     int `yaml:"cpus"`
}

type ValidatorCfg struct {
	Path string `yaml:"path"`
}

type Capability struct {
	ExpectedBTF bool `yaml:"expected_btf"`
}

func LoadProfile(path string) (Profile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Profile{}, fmt.Errorf("read profile: %w", err)
	}

	var p Profile
	if err := yaml.Unmarshal(data, &p); err != nil {
		return Profile{}, fmt.Errorf("parse profile YAML: %w", err)
	}

	if err := ValidateProfile(p); err != nil {
		return Profile{}, err
	}
	return p, nil
}
