package vm

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

type Profile struct {
	ID           string `yaml:"id"`
	Distro       string `yaml:"distro"`
	Version      string `yaml:"version"`
	KernelFamily string `yaml:"kernel_family"`
	Arch         string `yaml:"arch"`
	Runner       string `yaml:"runner,omitempty"`
	// InstallKernel installs a specific kernel release inside the guest
	// before validation and reboots into it, so one base image yields a
	// dense per-release matrix instead of only the kernel the image
	// shipped with. Debian-family (apt/grub) and RHEL-family (dnf/grubby)
	// profiles are supported; the release must be a package-exact string
	// such as "5.15.0-118-generic" or "5.14.0-687.26.1.el9_8.x86_64".
	InstallKernel string `yaml:"install_kernel,omitempty"`
	// KernelPackages lists direct package URLs (.deb or .rpm) to install
	// instead of going through the package manager's indexes. Required for
	// kernel releases the distro has superseded: they remain downloadable
	// in the archive pool but disappear from the indexes. Generated by
	// `bpfcompat kernel-sweep` from the kernel-crawler inventory.
	KernelPackages []string       `yaml:"kernel_packages,omitempty"`
	Image          ImageConfig    `yaml:"image"`
	VirtmeNG       VirtmeNGCfg    `yaml:"virtme_ng,omitempty"`
	Firecracker    FirecrackerCfg `yaml:"firecracker,omitempty"`
	Boot           BootConfig     `yaml:"boot"`
	Validator      ValidatorCfg   `yaml:"validator"`
	Capabilities   Capability     `yaml:"capabilities"`
}

type ImageConfig struct {
	SourceURL string `yaml:"source_url"`
	LocalPath string `yaml:"local_path"`
	// SHA256 optionally pins the expected image digest. When set, a
	// downloaded or cached image that does not match fails the run instead
	// of silently testing different bytes. Pinning requires a
	// release-versioned source_url — vendor "current" URLs mutate.
	SHA256 string `yaml:"sha256,omitempty"`
}

type VirtmeNGCfg struct {
	Run       string   `yaml:"run"`
	ExtraArgs []string `yaml:"extra_args,omitempty"`
}

type FirecrackerCfg struct {
	KernelImagePath string `yaml:"kernel_image_path"`
	RootfsPath      string `yaml:"rootfs_path,omitempty"`
	InitrdPath      string `yaml:"initrd_path,omitempty"`
	BootArgs        string `yaml:"boot_args,omitempty"`
	GuestMAC        string `yaml:"guest_mac,omitempty"`
	TapDevice       string `yaml:"tap_device,omitempty"`
}

type BootConfig struct {
	MemoryMB int `yaml:"memory_mb"`
	CPUs     int `yaml:"cpus"`
}

type ValidatorCfg struct {
	Path string `yaml:"path"`
}

type Capability struct {
	ExpectedBTF bool `yaml:"expected_btf"`
}

func LoadProfile(path string) (Profile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Profile{}, fmt.Errorf("read profile: %w", err)
	}

	var p Profile
	if err := yaml.Unmarshal(data, &p); err != nil {
		return Profile{}, fmt.Errorf("parse profile YAML: %w", err)
	}

	if err := ValidateProfile(p); err != nil {
		return Profile{}, err
	}
	return p, nil
}

// Kernel install families. A profile's distro determines how a specific
// kernel release is installed inside the guest and how the next boot is
// selected: apt plus grub menu titles on the Debian family, dnf plus grubby
// on the RHEL family.
const (
	KernelFamilyDebian = "debian"
	KernelFamilyRHEL   = "rhel"
)

// KernelInstallFamily maps a profile distro to its kernel install family, or
// "" when kernel-sweep does not support the distro. Deliberately excluded:
// oracle (UEK ships from its own repositories, not BaseOS), immutable or
// image-based systems (rhcos, fedora-coreos, flatcar, bottlerocket, talos),
// and the mainline/CI kernel profiles, which are built rather than packaged.
func KernelInstallFamily(distro string) string {
	switch strings.ToLower(strings.TrimSpace(distro)) {
	case "ubuntu":
		return KernelFamilyDebian
	case "almalinux", "rocky", "centos-stream", "rhel":
		return KernelFamilyRHEL
	default:
		return ""
	}
}
